### ISSUE TITLE
Need to disable no-loop-func for an exceptional case

### ISSUE THREAD

**Issue by manasisharma** [FlexShopper/eslint-config-flexshopper#30]
do {
         /* eslint-disable no-loop-func */
         sqs.receiveMessage(receiveMessageParams, (err, reply) => {
             messages = reply;
          });
         /* eslint-enable no-loop-func */
     }
     while ((messages === undefined) ||
      (messages.Messages === undefined) ||
      (messages.Messages.length < 1));

**Comment by italoacasas** [comment]
Thanks @manasisharma
