### ISSUE TITLE
does not detect unused variables

### ISSUE THREAD

**Issue by onel0p3z** [FlexShopper/eslint-config-flexshopper#31]
http://eslint.org/docs/rules/no-unused-vars

Running eslint on this file should return `unused` vars error

https://github.com/FlexShopper/FlexMarket/blob/development/server/server.js

**Comment by jstop** [comment]
I'm seeing this error which is probably related to this topic.
```Error: flexshopper/index.js:
	Configuration for rule "no-unused-vars" is invalid:
	Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").```
